commit.version=${buildNumber}

# log
quarkus.banner.enabled=false
quarkus.log.category."io.quarkus".level=ERROR
quarkus.log.console.format=%s%e%n

# native
quarkus.native.additional-build-args=-H:ReflectionConfigurationFiles=reflection-config.json,\
--trace-class-initialization=jdk.internal.net.http.HttpClientImpl\\,jdk.internal.net.http.common.Utils\\,org.kohsuke.github.connector.GitHubConnector\\,java.net.Inet4Address\\,java.net.Inet6Address,\
--initialize-at-run-time=jdk.internal.net.http.HttpClientImpl\\,jdk.internal.net.http.common.Utils\\,org.kohsuke.github.connector.GitHubConnector\\,java.net.Inet4Address\\,java.net.Inet6Address\\,com.sun.jndi.dns.DnsClient,\
--trace-object-instantiation=java.net.Inet4Address\\,java.net.Inet6Address
#quarkus.native.additional-build-args=-H:PrintFlags=
quarkus.native.auto-service-loader-registration=true